version: '3'

services:
  node:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3200:3200"
    command: npm start
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites/
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - node
    networks:
      - app-network

networks:
  app-network:
    driver: bridge