version: '3'

services:
  node:
    image: ghcr.io/dlozina/deploy-test-node:latest
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app-network

  nginx:
    image: ghcr.io/dlozina/deploy-test-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - ./.htpasswd:/etc/nginx/.htpasswd:ro
       - ./ssl:/etc/nginx/ssl:ro
    restart: always
    depends_on:
      - node
    networks:
      - app-network

networks:
  app-network:
    driver: bridge